package srcs;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srcs/proto/srcs.Message.proto

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListChatter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListChatter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030srcs/proto/srcs.Message.proto\032\036google/proto" +
      "buf/wrappers.proto\032\033google/protobuf/empt" +
      "y.proto\"2\n\004SubM\022\016\n\006pseudo\030\001 \001(\t\022\014\n\004host\030" +
      "\002 \001(\t\022\014\n\004port\030\003 \001(\005\"(\n\005SendM\022\016\n\006pseudo\030\001" +
      " \001(\t\022\017\n\007message\030\002 \001(\t\"\033\n\013ListChatter\022\014\n\004" +
      "list\030\001 \003(\t2\337\001\n\006Server\022.\n\tsubscribe\022\005.Sub" +
      "M\032\032.google.protobuf.BoolValue\022+\n\004send\022\006." +
      "srcs.SendM\032\033.google.protobuf.Int32Value\0223\n\013li" +
      "stChatter\022\026.google.protobuf.Empty\032\014.List" +
      "Chatter\022C\n\013unsubscribe\022\034.google.protobuf" +
      ".StringValue\032\026.google.protobuf.Empty26\n\006" +
      "Client\022,\n\nnewMessage\022\006.srcs.SendM\032\026.google.pr" +
      "otobuf.EmptyB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_SubM_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubM_descriptor,
        new java.lang.String[] { "Pseudo", "Host", "Port", });
    internal_static_SendM_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendM_descriptor,
        new java.lang.String[] { "Pseudo", "srcs.Message", });
    internal_static_ListChatter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListChatter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListChatter_descriptor,
        new java.lang.String[] { "List", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
