package srcs;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srcs/proto/srcs.Message.proto

public interface SendMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.SendM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pseudo = 1;</code>
   */
  java.lang.String getPseudo();
  /**
   * <code>string pseudo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudoBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
