package srcs;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srcs/proto/srcs.Message.proto

public interface SubMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.SubM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pseudo = 1;</code>
   */
  java.lang.String getPseudo();
  /**
   * <code>string pseudo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudoBytes();

  /**
   * <code>string host = 2;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
